/* PROPERTY OF THE TRAILERPARK DO NOT ATTEMPT TO STEAL CONTENT*/
if(playerSide != civilian) exitWith {};
private ["_camera", "_camDistance","_randCamY","_randCamZ","_camTime"];
_camDistance = 700;_randCamY = 75 - floor(random 150);
_randCamZ = 75 - floor(random 150);
playsound "intro";
_onScreenTime = 4;
_role1 = "Seja bem-vindo";
_role1names = ["aproveitar a sua estadia!"];
{_memberFunction = _x select 0;_memberNames = _x select 1;_finalText = format ["<t size='1.00' color='#3399ff' align='right'>%1<br /></t>", _memberFunction];_finalText = _finalText + "<t size='0.70' color='#FFFFFF' align='right'>";{_finalText = _finalText + format ["%1<br />", _x]} forEach _memberNames;_finalText = _finalText + "</t>";_onScreenTime + (((count _memberNames) - 1) * 0.5);[_finalText,[safezoneX + safezoneW - 0.8,0.50],[safezoneY + safezoneH - 0.8,0.7],_onScreenTime,0.5] spawn BIS_fnc_dynamicText;} forEach 
[[_role1, _role1names]];
_camTime = 15;
_camera = "camera" camCreate [3290.04-_camDistance,13380,-25];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.7;
_camera camCommit 0;
waitUntil {camCommitted _camera};
_camera camSetTarget [3290.04,13380,10];
_camera camSetRelPos [0,0,0];
_camera camCommit _camTime;waitUntil {camCommitted _camera};
_camera cameraEffect ["terminate","back"];
camDestroy _camera;
_onScreenTime = 3;
_role1 = "Website:";
_role1names = ["www.undeadbrasil.com"];
{_memberFunction = _x select 0;_memberNames = _x select 1;_finalText = format ["<t size='1.0' color='#3399ff' align='right'>%1<br /></t>", _memberFunction];_finalText = _finalText + "<t size='0.70' color='#FFFFFF' align='right'>";{_finalText = _finalText + format ["%1<br />", _x]} forEach _memberNames;
_finalText = _finalText + "</t>";_onScreenTime + (((count _memberNames) - 1) * 0.5);
[_finalText,[safezoneX + safezoneW - 0.8,0.50],[safezoneY + safezoneH - 0.8,0.7],_onScreenTime,0.5] spawn BIS_fnc_dynamicText;} forEach 
[[_role1, _role1names]];
_camTime = 7;_camera = "camera" camCreate [3611.73,12980,30];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.7;_camera camCommit 0;
waitUntil {camCommitted _camera};
_camera camSetTarget [3611.73,13080,25];
_camera camSetRelPos [0,0,0];
_camera camCommit _camTime;
waitUntil {camCommitted _camera};
_camera cameraEffect ["terminate","back"];
camDestroy _camera;_role1 = "Teamspeak 3:";
_role1names = ["ts3.undeadbrasil.com"];
{_memberFunction = _x select 0;
_memberNames = _x select 1;
_finalText = format ["<t size='1.0' color='#3399ff' align='right'>%1<br /></t>", _memberFunction];
_finalText = _finalText + "<t size='0.70' color='#FFFFFF' align='right'>";
{_finalText = _finalText + format ["%1<br />", _x]} forEach _memberNames;
_finalText = _finalText + "</t>";_onScreenTime + (((count _memberNames) - 1) * 0.5);
[_finalText,[safezoneX + safezoneW - 0.8,0.50],[safezoneY + safezoneH - 0.8,0.7],_onScreenTime,0.5] spawn BIS_fnc_dynamicText;
} forEach 
[[_role1, _role1names]];
_camTime = 7;_camera = "camera" camCreate [20788.2,6733.6,2];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.7;
_camera camCommit 0;
waitUntil {camCommitted _camera};
_camera camSetTarget [20802.4,6783.28,2];
_camera camSetRelPos [0,0,0];
_camera camCommit _camTime;
waitUntil {camCommitted _camera};
_camera cameraEffect ["terminate","back"];
camDestroy _camera;
_role1 = "Quer se tornar um Policial?";
_role1names = ["Acesse no forum!"];
{_memberFunction = _x select 0;_memberNames = _x select 1;_finalText = format ["<t size='1.0' color='#3399ff' align='right'>%1<br /></t>", _memberFunction];
_finalText = _finalText + "<t size='0.70' color='#FFFFFF' align='right'>";
{_finalText = _finalText + format ["%1<br />", _x]} forEach _memberNames;
_finalText = _finalText + "</t>";
_onScreenTime + (((count _memberNames) - 1) * 0.5);
[_finalText,[safezoneX + safezoneW - 0.8,0.50],[safezoneY + safezoneH - 0.8,0.7],_onScreenTime,0.5] spawn BIS_fnc_dynamicText;
} forEach [[_role1, _role1names]];
_camTime = 7;_camera = "camera" camCreate [7947.11,16008.9,2];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.7;
_camera camCommit 0;
waitUntil {camCommitted _camera};
_camera camSetTarget [8143.12,15900.4,2];
_camera camSetRelPos [0,0,0];
_camera camCommit _camTime;
waitUntil {camCommitted _camera};
_camera cameraEffect ["terminate","back"];
camDestroy _camera;_role1 = "";
_role1names = ["Follow our rules, have fun!"];
{_memberFunction = _x select 0;_memberNames = _x select 1;
_finalText = format ["<t size='1.0' color='#FFFFFF' align='right'>%1<br /></t>", _memberFunction];
_finalText = _finalText + "<t size='0.70' color='#FFFFFF' align='right'>";
{_finalText = _finalText + format ["%1<br />", _x]} forEach _memberNames;
_finalText = _finalText + "</t>";
_onScreenTime + (((count _memberNames) - 1) * 0.5);
[_finalText,[safezoneX + safezoneW - 0.8,0.50],[safezoneY + safezoneH - 0.8,0.7],_onScreenTime,0.5] spawn BIS_fnc_dynamicText;} forEach [[_role1, _role1names]];
_camTime = 4;_camera = "camera" camCreate [(position player select 0), (position player select 1),(position player select 2)+500];
_camera cameraEffect ["internal","back"];
_camera camSetFOV 0.7;
_camera camCommit 0;
waitUntil {camCommitted _camera};
_camera camSetTarget vehicle player;
_camera camSetRelPos [0,0,2];
_camera camCommit _camTime;
waitUntil {camCommitted _camera};
_camera cameraEffect ["terminate","back"];
camDestroy _camera;
life_firstSpawn = false;
[] call life_fnc_InfoMenu;
